[env:seeed_xiao_esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.31/platform-espressif32.zip
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
board_build.partitions = extras/partitions.csv
build_flags =
    -I.
    -DCAMERA_MODEL_XIAO_ESP32S3
